### PR TITLE
hide vertical overflow on graphics

### PR DESCRIPTION
**Pull request by raftelti**

### CODE REVIEW

**Comment by jugoncalves** [comment]
Hm, why?

**Comment by raftelti** [comment]
overflow

**Comment by jugoncalves** [comment]
Ah, ok. Which browser/OS?

**Comment by raftelti** [comment]
Chrome 43 on Window 8.1

**Comment by jugoncalves** [comment]
Thanks :smile:

**Comment by raftelti** [comment]
you're welcome! o/

**Comment by willianjusten** [comment]
Oh, I love Windows...-.-

**Pull request merged**
